site_name: TidalCycles
site_url: https://doc.tidalcycles.org/
theme:
  name: material
  language: en
  palette:
    primary: teal
    accent: pink
  repo_url: https://github.com/tidalcycles/tidal-doc
  features:
    - search.suggest
    - search.highlight
    - search.share
  custom_dir: material-custom/
extra_javascript:
  - javascripts/header.js
extra_css:
  - stylesheets/header.css
plugins:
  - search

copyright: '&copy; 2020 contributors, CC BY-SA'

extra:
  languages:
    - name: English
      lang: en
    - name: Deutsch
      lang: de
    - name: 日本語
      lang: ja

  social:
    - icon: fontawesome/brands/discourse
      link: 'https://club.tidalcycles.org'
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ugFq7KfGnB
    - icon: fontawesome/brands/github
      link: 'https://github.com/tidalcycles'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/tidalcycles'
    - icon: fontawesome/brands/youtube
      link: 'https://youtube.com/tidalcycles'
    - icon: fontawesome/brands/mastodon
      link: 'https://post.lurk.org/@tidalcycles'

# from patchbox os - useful?
markdown_extensions:
  - meta
  - toc:
      permalink: ''
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - footnotes

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - How-To guides: howtos.md
  - Background: background.md
  - Reference: reference.md
  - Community: community.md
  # - Raspberry Pi Essentials:
  #     - Install the Operating System to the SD Card: install-os-to-sd-card.md
  #     - Find the IP Address: find-the-ip-address.md
  #     - Remote Control Options: remote-control.md
  # - First Run:
  #     - First Run Options: first-run-options.md
  #     - Setup Wizard: setup-wizard.md
  # - Modules:
  #     - Modules: modules.md
  #     - Creating a Module: creating-a-module.md
  #     - patchbox-module.json reference: patchbox-module-json.md
  # - Software Guides: software-guides.md
  # - amidiauto: amidiauto.md
  # - Troubleshooting: troubleshooting.md
